installer.title=Recobbled Fabric Installer
option.create.profile=Create profile
progress.done=Done
progress.exception.no.launcher.directory=No launcher directory found!
progress.exception.no.launcher.profile=No launcher profile.json found!
progress.installing=Installing Recobbled Fabric {0}
prompt.exception.occurrence=Exception occurred!
prompt.install=Install
prompt.loader.version=Loader Version:
prompt.launcher.type.body=Recobbled Fabric has detected 2 different installations of the Minecraft Launcher, which launcher do you wish to install Fabric to?\n\n- Select Microsoft Store if you are playing Minecraft through the Xbox App or the Windows Store.\n- Select Standalone if you downloaded the Minecraft launcher directly from the Minecraft.net website.\n\nIf you are unsure try the Microsoft Store option first, you can always re-run the installer.
prompt.launcher.type.xbox=Microsoft Store / Xbox
prompt.launcher.type.win32=Standalone (Win32)
prompt.game.version=MC Recobbled Version:
prompt.ready.install=Ready to install
prompt.select.location=Launcher Location:
prompt.install.successful.title=Successfully Installed
prompt.install.successful=Fabric Loader {0} for {1} has successfully been installed.
tab.client=Client

# Link Reference

recobbled.manifest=https://github.com/Recobbled-Fabric/Vanilla-Installer/raw/refs/heads/resource/recobbled_version_v2.json
fabric.maven=https://maven.fabricmc.net/
fabric.loader.manifest=https://meta.fabricmc.net/v2/versions/loader
fabric.loader.artifact=net.fabricmc:fabric-loader:

